# Generated by Django 5.1.4 on 2025-03-21 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=255, verbose_name='EMAIL_BACKEND')),
                ('email_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST')),
                ('email_port', models.IntegerField(default=587, verbose_name='EMAIL_PORT')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='EMAIL_USE_TLS')),
                ('email_host_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST_USER')),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='EMAIL_HOST_PASSWORD')),
                ('default_from_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='DEFAULT_FROM_EMAIL')),
                ('ativar_notificacoes', models.BooleanField(default=False, verbose_name='Ativar notificações')),
                ('email_notificacao', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email para notificações')),
            ],
            options={
                'verbose_name': 'Configuração de Email',
                'verbose_name_plural': 'Configurações de Email',
            },
        ),
        migrations.CreateModel(
            name='PlanoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('nivel', models.CharField(choices=[('nivel1', 'Nível 1 - Básico'), ('nivel2', 'Nível 2 - Intermediário'), ('nivel3', 'Nível 3 - Avançado')], max_length=10, verbose_name='Nível')),
                ('recursos', models.TextField(max_length=500, verbose_name='Recursos')),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('empresa', models.CharField(max_length=100, verbose_name='Empresa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('status_pagamento', models.CharField(choices=[('em_dia', 'Em dia'), ('atraso', 'Em atraso'), ('expirado', 'Expirado')], default='em_dia', max_length=10, verbose_name='Status de Pagamento')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planoassinatura', verbose_name='Plano')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Contagem de uso')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_meta', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Metadados de API Key',
                'verbose_name_plural': 'Metadados de API Keys',
            },
        ),
    ]
